/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-07 at 09:18:10 UTC 
 * Modify at your own risk.
 */

package com.jtristan.librosendpoint.entidades.libroendpoint.model;

/**
 * Model definition for Libro.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the libroendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Libro extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String autor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String isbn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer puntuacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String titulo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("usuario_logeado")
  private User usuarioLogeado;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAutor() {
    return autor;
  }

  /**
   * @param autor autor or {@code null} for none
   */
  public Libro setAutor(java.lang.String autor) {
    this.autor = autor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Libro setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIsbn() {
    return isbn;
  }

  /**
   * @param isbn isbn or {@code null} for none
   */
  public Libro setIsbn(java.lang.String isbn) {
    this.isbn = isbn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPuntuacion() {
    return puntuacion;
  }

  /**
   * @param puntuacion puntuacion or {@code null} for none
   */
  public Libro setPuntuacion(java.lang.Integer puntuacion) {
    this.puntuacion = puntuacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitulo() {
    return titulo;
  }

  /**
   * @param titulo titulo or {@code null} for none
   */
  public Libro setTitulo(java.lang.String titulo) {
    this.titulo = titulo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public User getUsuarioLogeado() {
    return usuarioLogeado;
  }

  /**
   * @param usuarioLogeado usuarioLogeado or {@code null} for none
   */
  public Libro setUsuarioLogeado(User usuarioLogeado) {
    this.usuarioLogeado = usuarioLogeado;
    return this;
  }

  @Override
  public Libro set(String fieldName, Object value) {
    return (Libro) super.set(fieldName, value);
  }

  @Override
  public Libro clone() {
    return (Libro) super.clone();
  }

}
